### PR TITLE
V0.10.1

### PR DESCRIPTION
**Pull request by johnveitch**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Update to CPNest [v0.10.1](https://github.com/johnveitch/cpnest/releases/tag/v0.10.1)

### CODE REVIEW

**Comment by johnveitch** [comment]
> @johnveitch, why did you change the conda package to use git as opposed to pypi?

I changed CPNest's CI to automatically push Github releases to PyPI. By taking the release from Github rather than PyPI this can be done in parallel, and it avoids having to copy around these long hashes.

**Comment by duncanmmacleod** [comment]
conda-forge has a magic bot that automatically scrapes new releases from pypi and automatically posts PRs for feedstocks to update them. If you revert back to referencing tarballs on pypi.python.org you will just have to merge PRs for new releases, rather than opening them yourself.

It is generally considered better practice to use tarballs and checksums in conda recipes, rather than git references.

**Comment by duncanmmacleod** [comment]
> > conda-forge has a magic bot that automatically scrapes new releases from pypi and automatically posts PRs for feedstocks to update them. If you revert back to referencing tarballs on pypi.python.org you will just have to merge PRs for new releases, rather than opening them yourself.
> 
> It doesn't seem to have happened for previous releases. The pull requests for new versions have all been made manually. Is there something I have to set up?
No, it should 'just happen', its odd that it doesn't seem to have happened. Sometimes there can be a delay of up to a few hours, perhaps we've just done it manually too quickly and the automatic PRs were cancelled.
> 
> > It is generally considered better practice to use tarballs and checksums in conda recipes, rather than git references.
> 
> I don't really mind but the latter is more convenient if we are doing it manually.
Fair enough. If you are going to manage the conda feedstock yourself, which is totally fine with me, then its entirely up to you how you run it.

**Comment by johnveitch** [comment]
OK, I think I have the hang of doing it myself now but I will look into this automatic thing when I am preparing to make another release.

**Pull request merged**
